name: Changelog

on:
  push:
    branches:
      - main
      - develop

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): {version} [skip ci]'
          preset: 'angular'
          tag-prefix: 'v'
          output-file: 'CHANGELOG.md'
